name: Deploy Frontend to ServerPlus

on:
  push:
    branches:
      - main # Если ваша главная ветка называется master, замените main на master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: '185.196.218.176' # IP вашего сервера
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Ключ мы добавим в GitHub на следующем шаге
          script: |
            cd /var/www/html/frontend
            git pull origin main
            npm install
            CI=true npm run build
